### ISSUE TITLE
Poor randomisation function?

### ISSUE THREAD

**Issue by Xommers** [ArtemGr/Sidekick#10]
Loving the bot so far, but recently discovered that it's prone to 'streaks', batches of consecutive numbers or results within 1 of each other. I rolled 100dX a few times and every batch of rolls had 5+ such streaks, such as 100d20 resulting in +10+8+10+7+10+10+10+9+10+10+10 and later in the same batch +17+17+17+18+17. Far from impossible but it's statistically unlikely for this to happen more than once per 100dX batch of rolls. A pattern is clearly visible, which kind of defeats the point of randomization. I would recommend creating a more robust and varied seed function from which to derive numbers.
salty af on account of critically fumbling three times in a row due to this.

Thanks for considering this issue.

**Comment by ArtemGr** [comment]
Thanks for the heads up.

The seed is /dev/urandom, according to the docs (https://github.com/rust-lang-nursery/rand). It should be good enough.

What I might be missing is reusing a generator instance instead of just spamming a static function.

I'll see if I can reproduce this.

**Comment by ArtemGr** [comment]
![you can never be sure](https://www.random.org/analysis/dilbert.jpg)

**Comment by ArtemGr** [comment]
So I did a small test

```
  let mut longest_streak = 0;
  let mut streak = 0;
  let mut prev = 0;
  for _ in 0..99 {
    let r = roll (10);
    if r == prev {streak += 1; if streak > longest_streak {longest_streak = streak}} else {prev = r; streak = 0}}
  println! ("longest_streak: {}", longest_streak);
  assert! (longest_streak < 3, "largest_streak: {}", longest_streak);
```

and I can't I reproduce the phenomena. The number of streaks I encounter looks normal to me, I don't see a bias.

Cursory examination of the logs doesn't give anything either.

---

Now, it's not a crime if the random number generator produces the same number now and then. Such streaks stand out to our perception but they are in no way a proof of poor randomness.

I would like to, but I didn't have the time to go over the tests in https://www.random.org/analysis/ (I have, in fact, downloaded and compiled the NIST test suite, but it's command line interface is lacking in user-friendliness and can't be used without digging further into the sources and/or the paper).

On a side note I'd like to mention "A Basic Introduction to Probability" section [in the Angry's article](http://theangrygm.com/probability-for-gamers/).

And [a funny scene from "Rosencrantz and Guildenstern Are Dead"](https://www.youtube.com/watch?v=NbInZ5oJ0bc), a  film by Tom Stoppard.

**Comment by ArtemGr** [comment]
To quote Angry: "*In essence, probability about determining the chance of a given outcome of an event. But that probability doesn’t erase the fact that the event is random. You might have a 95% chance of hitting the goblin on your next attack roll, but that doesn’t mean you can’t roll a 1. And it might be very unlikely, but you can roll three 1s in a row.*

*You can design a system wherein the players will succeed on 80% of their actions, but any given action might succeed and it might fail and any player might get a run of really bad or really good luck. The outcomes are still random.*

*When an individual player talks about probabilities, they usually want to know the chance of getting a specific outcome. What’s the chance I’ll roll a 15 for my Strength score if I roll 3d6? If I roll 4d6? What’s the chance I’ll get a 10 or above? What are the chances I’ll manage to kill this goblin this round? And the problem with those questions is that they are talking about a SINGLE EVENT.*"

**Comment by ArtemGr** [comment]
FYI, https://www.reddit.com/r/rust/comments/87qy40/history_of_the_rand_crate/

**Comment by ArtemGr** [comment]
https://en.wikipedia.org/wiki/Clustering_illusion

**Comment by ArtemGr** [comment]
“Finally, psychologists have demonstrated that humans have a very poor intuitive understanding of randomness. We struggle to comprehend the fact that HHHHH is just as likely an outcome of five coin tosses as HTHTT. This seems to be the source of a whole range of biases impacting our decision-making.” - https://www.menimagerie.com/manuscripts/2018/6/9/viii-bayes-and-brains
