### ISSUE TITLE
Memorized Rolls broken outright

### ISSUE THREAD

**Issue by dalek955** [ArtemGr/Sidekick#101]
Noticed when I tried to use Sidekick for a game this morning: Memorized Rolls is now refusing to retain anything at all. When I create a memorized roll, it appears to work fine, but it's not there when I try to invoke that roll later, or even right away.
![memorized rolls not working](https://user-images.githubusercontent.com/33106995/35771874-74fe1ce0-08e8-11e8-976d-e86636ad17b4.png)
We tried booting and then reinviting Sidekick, but it didn't help.

**Comment by ArtemGr** [comment]
Thanks for the heads-up!

There was a database outage yesterday.

I'm working on a more reliable (replicated) database solution.
