### ISSUE TITLE
Bot down? Is there a way to restart it?

### ISSUE THREAD

**Issue by HolyRage** [ArtemGr/Sidekick#104]
Hello there, I am a Discord newbie and just created my own server, having chosen Sidekick as its dice bot. Unfortunately, the bot seems down, any way to restart/see if it's online?

Thank you for being patient!

**Comment by laeraor** [comment]
this is also happening to me.  the bot is online but not responding to any of the commands

**Comment by ArtemGr** [comment]
Sorry about that.
