### ISSUE TITLE
Broken Bot

### ISSUE THREAD

**Issue by LimitedSanity** [ArtemGr/Sidekick#106]
Hello. Just noticed this issue today. I use the bot to roll die.

/r 4d10!>=5f1 #Stamina check

stuff like that...

Thought you would like to know that it works if I send a private message but not in the server. I triple checked all of the permissions and settings and did a few kick/re-invites fro good measure. Still not working in the server.

**Comment by LimitedSanity** [comment]
Also - I tried on more than one server that uses it and the same issue occurs.

**Comment by akiortagem** [comment]
Can confirm. Bot does not respond to any command now, but only on some servers I'm in. Private Message worked, but only up to 10 mins ago.

**Comment by LimitedSanity** [comment]
Can double confirm. Running a solo game with one of my players and it worked less than 15 minutes ago. Now it is not working in private chat or any server.

**Comment by ArtemGr** [comment]
Thanks for the heads up.

**Comment by LimitedSanity** [comment]
Just started working for me
