### ISSUE TITLE
sidekick dice roll delays

### ISSUE THREAD

**Issue by chezz896** [ArtemGr/Sidekick#126]
Hi,

Could I ask what would be a solution for sidekick having delays in showing results of dice rolls? Currently we are having an ongoing game and I'm using sidekick. I rolled and then got the result after around 20 minutes. Thanks

**Comment by SUTempest** [comment]
Pretty much the same as above. We've experienced one 30 minute delay from entering a roll command to getting Sidekick's response, and failures to respond entirely on subsequent attempts. I'm not certain there's anything we as end users can do; simply drawing attention to the issue and confirming it's not just one person.

**Comment by ArtemGr** [comment]
We've seen temporary delays in #120. Might be a Discord and/or internet connectivity issue.
As usual, providing the exact timestamp when the problem was observed might help.

**Comment by ArtemGr** [comment]
Closing as answered.

**Comment by ArtemGr** [comment]
cf #129
