### ISSUE TITLE
Fate Dice / Xdf

### ISSUE THREAD

**Issue by arcandio** [ArtemGr/Sidekick#13]
I't be nice to have Fate dice, my Discord channel us mostly about Fate games that use Fate/Fudge dice (+/0/-)

**Comment by ArtemGr** [comment]
I never played a Fate game, but it's high time to remedy that. There are Star Wars games on Fate, right? Can you point me to something most representative to your cause?

**Comment by arcandio** [comment]
There are some hacks and mods, but no *official* game for Fate, that I know of. Most of the stuff I've seen for Star Wars has been Fate Accelerated Edition, which seems like the best possible fit of system to lore that I've ever heard of. I can easily imagine that being a blast.

As for the dice, we're using /r 1d6-1d6 right now, which just isn't quite the same as /r 4df.

**Comment by arcandio** [comment]
Oh, also, https://fate-srd.com is an excellent resource for learning Fate.

**Comment by ArtemGr** [comment]
Great, thanks!

**Comment by LordSalamander** [comment]
In case you were looking for appropriate syntax, the one used elsewhere is 1dF (rather than 1d6, for example), and we usually roll them in sets of 4 (thus, 4dF), although not always.

Cheers :)

**Comment by arcandio** [comment]
It also seems like I've gotten macros to work with `4df` with the F lowercase as well, if that matters.

**Comment by ArtemGr** [comment]
Thanks for the pointers, mates.

I've checked my local concacts but there's no Fate / Fudge dice as of yet. Maybe I should join something on giantitp or whatever. I want to get a bit of experience first-hand before putting it to the bot.

What kind of macros do you mean, @arcandio ? roll20.net macros? Some other kind of macros?

**Comment by arcandio** [comment]
Yeah, I mean my macros in Roll20, such as `/r 4df + ?{Bonus?|1}`. The capitalization thing isn't really a huge deal either way, though.

I don't know about Fudge, but in Fate (which is mostly Fudge-based, IIRC) there's only one roll mechanic, as @LordSalamander said, `4df`, so there isn't really any more to it than that. I'm not aware of any other systems that use dF for anything besides an actually +/-4 Fate-style roll, the dice themselves are pretty rare. compared to D&D multipacks and d20s and such. I think I've seen more crystal dice than `df` in my life as a roleplayer.

**Comment by arcandio** [comment]
@ArtemGr We've got occasional playtests for [Oubliette Second Edition](oubliette.voidspiral.com) going every once in a while if you'd like to drop by one of those. I don't know when our next one is, but I could run you through character creation and a oneshot if you wanted.

**Comment by ArtemGr** [comment]
That is wow-tastic, but to see the dice mechanics in action I'll probably just need a premade character / moster / NPC and do some out of the blue combat / social / whatever rolls. I think we'd better do this on Discord, I might try some rolls on the bot right away.

**Comment by arcandio** [comment]
Our Discord server is there on the Oubliette website if you want to drop by. We've got an unused RP channel and I'm on there all day while I work on the game.

**Comment by ArtemGr** [comment]
Thanks to @arcandio I've got my head around what Fudge dice is.
To me it's basically `1dF = 2-1d3`.
`4dF = (2-1d3) + (2-1d3) + (2-1d3) + (2-1d3)`.

The syntax is clear. Should add it soon.

A quesion. From what @arcandio said, I've got that "dF" shortcut is not super important (in fact, 1df is never used in Fate). Does that sound right?

**Comment by arcandio** [comment]
Possibly relevant links to other games where dF are used:  http://rpg.stackexchange.com/a/1818/26630

**Comment by LordSalamander** [comment]
Depends on the system being used. Sometimes seeing the individual rolls is important, other times it is not.

`1dF = 2-1d3` sounds about right, and I guess the `dF `notation is just due to convention more than anything else.

**Comment by ArtemGr** [comment]
What about "4df" as opposed to "4dF"? Do such slips/typos happen often?

**Comment by LordSalamander** [comment]
Either works. I've known people to do both. :)

**Comment by arcandio** [comment]
Having an option for `4df` as well as `4dF` saves me a keystroke at least.

**Comment by ArtemGr** [comment]
Thanks, @LordSalamander, @arcandio!
I think it's working now (screenshot: http://prntscr.com/dlw0y5).

**Comment by LordSalamander** [comment]
Yeah, it works great! Thanks @ArtemGr!

**Comment by arcandio** [comment]
Yaaay! Confirmed!
![image](https://cloud.githubusercontent.com/assets/2172188/21391148/f6de6124-c74f-11e6-907a-324204ee4956.png)
