### ISSUE TITLE
Sidekick offline on only one server

### ISSUE THREAD

**Issue by JadeMage** [ArtemGr/Sidekick#133]
Howdy, while playing a game over a long period of time, 10:40 ADT (UTC -3) we tried to make a roll and the bot just, didn't. It is still appearing offline there, even though it works on every other server I have running it, is there a way to reboot or reconnect it beyond kicking it and readding it (which has already been tried)?

**Comment by ArtemGr** [comment]
I've triggered restart of the shards, did it help?

**Comment by JadeMage** [comment]
It did, thanks a bunch!

**Comment by ArtemGr** [comment]
You're welcome!
Shards auto-restarting got turned off, I've just found out today. Turned it back on, the bot should be more stable once again.
Thanks for the heads up!
