### ISSUE TITLE
Sidekick adding ones in OVA

### ISSUE THREAD

**Issue by Archeo-Lumiere** [ArtemGr/Sidekick#143]
Exactly what it says, I rolled ova (5), got a three and four ones, and it gave me four, not three. I was just testing it, but finding this was important.

**Comment by DewOnTheGrass** [comment]
OVA addition doesn't determine the output by the highest face value rolled. Instead, it finds the sum of each face value rolled ((number of ones)*1,(number of twos)*2,(number of threes)*3,etc.), then returns whichever face value has the highest sum.

In other words, it doesn't look at your rolls and say "(3,1,1,1,1,2,2,2), 
3>1, 3>2, sum of all 3's = 3, return 3".

It looks at your rolls and says "(3,1,1,1,1,2,2,2), sum of threes = 3, sum of twos = 6, sum of ones = 4,
6>3, 6>4, return 6".

**Comment by Archeo-Lumiere** [comment]
While that may be, and honestly should be true, ones need to be an exception to the rule, as it is stated in the OVA manual that ones don't add together if they're your majority die.
