### ISSUE TITLE
Deck Feature Shows A Blue Circle In Place Of Suit..?

### ISSUE THREAD

**Issue by TimeBender25** [ArtemGr/Sidekick#144]
I recently learned about the deck feature, so I did some fooling around to see how it worked and it showed this:
![image](https://user-images.githubusercontent.com/10206717/46260364-d285b180-c4b2-11e8-84bd-30707aebf498.png)
 
I don't know why there's a blue circle, is it intentional to show Joker cards? Or is it accidental?

**Comment by ArtemGr** [comment]
Hi, @TimeBender25 !
This was proposed by the original Patreon patron backing this feature:

![](https://i.imgur.com/MsWH9uc.png)

**Comment by TimeBender25** [comment]
Thank you for the clarification! I was real confused.
