### ISSUE TITLE
Ability to move the bot to a specific channel

### ISSUE THREAD

**Issue by TheFiZi** [ArtemGr/Sidekick#15]
Right now it appears the bot dumps itself into the main chat channel.

I'd like to be able to move it to a sub channel on my Discord server.

**Comment by TheFiZi** [comment]
Nevermind. I found my issue.

**Comment by ArtemGr** [comment]
So what was it? Could you share for any other bot users who stumble there?

**Comment by TheFiZi** [comment]
The channel I wanted the bot in was configured so only members of a certain role could be in the channel. Once I figured that out all I had to do was add the bot to the role.

**Comment by ArtemGr** [comment]
Yep, it's the second time I see someone trying to use the bot in a private channel. I wonder if documentation should be updated to point out that only the public channels are by default visible to the bot. Thanks for the heads up.
