### ISSUE TITLE
Request: 10s Count Twice Option (Exalted 2e+)

### ISSUE THREAD

**Issue by meer0** [ArtemGr/Sidekick#151]
Hi! First of all thanks for the wonderful, super-useful program, been using it for fudge dice for years now. 

Just recently started up in Exalted again, and while there is the handy "/r 1d10>=7" command, there is unfortunately no option that I can see to make it so that 10s count twice. While not ALL rolls in Exalted use this system (i.e. damage, except by some Lunars) it would still be great; an extension on the theme of Exploding Dice, but just counting another success rather than actually prompting another roll.

Thanks again for this!

---
Todo list:
- [x] Parser test.
- [x] Parser.
- [x] Op test.
- [x] Op implementation.

**Comment by ArtemGr** [comment]
Hi, meer0! Nice to hear from you!
Do you have a syntaxis in mind for that doubling feature?

**Comment by ArtemGr** [comment]
Found a similar issue: #47.

**Comment by Esbilon** [comment]
Just chipping in to say I'd love to see this feature too. It's also used in all of the WoD 20th anniversary editions for specialties. If memory serves, some nWoD weapons have double 9s or double 8s for damage. I suggest a syntax like t10 (t for twice, 10 for the minimum number to count as two successes). So a roll with a specialty would be

/r 6d10>=6f1t10

**Comment by ArtemGr** [comment]
It works!
```
/r 1d1>=1t1
1d1>=1t1  = (1 1, 2 successes) = 2
```

**Comment by Esbilon** [comment]
Thanks a bunch!

**Comment by Sylordis** [comment]
Small question...
[BOT] Sidekick: @Sylordis:  `9d10>=6t10`  = (7 10 10 9 8 -5- -1- 10 10 9 -1-, 8 successes) = 8
Shouldn't it be 12? 8 normal successes + 4 from 10's?
