### ISSUE TITLE
Sidekick Bot down

### ISSUE THREAD

**Issue by Sarafelen** [ArtemGr/Sidekick#154]
I have several servers and on one of them the Sidekick bot suddenly just appears as offline and I cannot fix it. Everywhere else it's working I can even PM the bot without problems. Can you help me out? (I already tried kicking and reinviting the bot, fiexed nothing, problem stayed the same)

**Comment by ArtemGr** [comment]
Issued a full restart.

**Comment by Sarafelen** [comment]
Thx now it is back online and working!
