### ISSUE TITLE
Request: Fate Dice

### ISSUE THREAD

**Issue by LordSalamander** [ArtemGr/Sidekick#16]
Hey there, I love the dice bot. 

What would make it even more fantastic for my group is the addition of 'Fate Dice' (also called Fudge dice). They're basically three sided dice with -1, 0 and +1 on their sides. 

The syntax used elsewhere for that type of dice is 1dF (rather than 1d6, for example).

Cheers :)

**Comment by LordSalamander** [comment]
Realised that this was a repeat.

**Comment by ArtemGr** [comment]
> Hey there, I love the dice bot.

Thanks!

> What would make it even more fantastic for my group is the addition of 'Fate Dice' (also called Fudge dice).

Should be there soon.
