### ISSUE TITLE
Unable to Install

### ISSUE THREAD

**Issue by jacwalke** [ArtemGr/Sidekick#166]
When following the link to install Sidekick, which has always worked in the past but after a mistake Sidekick got kicked and that wasn't meant to happen, I am led to an unknown error page. Discord seems to be working just fine so I do not know why I am unable to install my favorite dice rolling bot.

**Comment by idarken** [comment]
same here

**Comment by jacwalke** [comment]
I don't know what the issue is but it seems to have resolved itself now.
