### ISSUE TITLE
Roll without specifying number of die

### ISSUE THREAD

**Issue by actualjellyfish** [ArtemGr/Sidekick#17]
When you use the command `/r d20`, the bot ignores the d and just spits out the number, 20. Instead of needing to specify `/r 1d20`, shouldn't a roll without a number just roll one of that die?

**Comment by ArtemGr** [comment]
Ouch. It's a bug, introduced by recent changes (I suspect #11). Will fix.

**Comment by actualjellyfish** [comment]
After I posted this I remembered to check the closed issues and saw that it was already there and was confused. Thanks!

**Comment by ArtemGr** [comment]
> I remembered to check the closed issues

You're good. Very good.

**Comment by ArtemGr** [comment]
Thanks for the eye-opener. I've bred a new strand of monkeys and they are much better at speaking dice.
