### ISSUE TITLE
rerolls in macro sometimes fail initially, and sometimes fail on repeats

### ISSUE THREAD

**Issue by ExxarKhun** [ArtemGr/Sidekick#179]
This macro
STATSET7
repeat (5d6r1k3, 7)

results when 1's occur vary.  Most of the time the initial 1's are rerolled.  Sometimes if the initial rolls have more than 1 '1' in a row, it fails to reroll them all.   Sometimes when the reroll of a 1 is also a 1, then it fails to reroll it again  (but sometimes it works).

![image](https://user-images.githubusercontent.com/30312402/55282229-7511d680-5316-11e9-973f-84ce1e0ba153.png)

The intent of the macro is to roll 5d6, reroll any 1's until the result is not a 1, and then take highest 3 results and sum.  (and do that 7 times)

**Comment by ArtemGr** [comment]
Closing in favor of #209.
