### ISSUE TITLE
Help command

### ISSUE THREAD

**Issue by eastwood6510** [ArtemGr/Sidekick#18]
Hey, this isn't an issue, more like a feature request.

I was thinking a simple /help command would be helpful.

Either it would display something like your readme file or even just point people to your readme file here on GitHub.

Just a thought.

**Comment by ArtemGr** [comment]
Hey and welcome to GitHub!

A help command like that it would be nice, of course, but we're not the only bot around, you know? There are tons of bots around and some of them are using the "/help" shortcut, no doubt.

It might be just the bad programming habits, like not polluting the global namespace, but adding more shortcut like that just doesn't sit well with me. Googling "namespace pollution" might tell you more of where I'm coming from.

We have "/r help" already, try it out, though it might be quite a bit outdated.

What I'm thinking is that "/r" without arguments should probably display the help. And of course we'd need a better help message.

What I'm really excited though is the idea of channeling any messsages addressed to Sidekick to a support chat. Talking with the dev should be as simple as saying "@ Sidekick, something". It's not directly related to actually *providing* help, just something that would be *fun* to have. And it's deep in the list of other dev tasks I have queued. But it's something I'm really looking forward to.  : >

**Comment by eastwood6510** [comment]
> It might be just the bad programming habits, like not polluting the global namespace, but adding more shortcut like that just doesn't sit well with me

I agree completely. 
Your suggestion of /r help sounds good, I checked out it since I didn't know about that previously and received an output that wasn't very...user friendly? Lol

> /roll [$name] ${pool}d${dice}[+${modifier}] [$comment]

I think just "/r" would be good too.

> Talking with the dev should be as simple as saying "@ Sidekick, something"

Now THAT is something I wish every bot had, though that would perhaps lead to developers of bots that are used on many servers to quickly go crazy lol.

**Comment by ArtemGr** [comment]
The "/r" command now prints some help!
