### ISSUE TITLE
[Feature Request] Repeat sum|success

### ISSUE THREAD

**Issue by TheMather1** [ArtemGr/Sidekick#181]
A functionality that would be very useful would be the ability to sum up or evaluate the results of a repeat roll, like so:
`/r repeat(1d20+1, 5, sum)`
> (11+1)+(17+1)+(1+1)+(6+1)+(15+1) = 55

And:
`/r repeat(2d20, 5, >10)`
> (~~9~~ 15 23 ~~8~~ 35, 3 Successes)

**Comment by ArtemGr** [comment]
Sounds good, but the extra argument might not be necessary with something like `/r repeat (2d20>10, 5)`.

**Comment by ArtemGr** [comment]
`/r repeat (2d6, 2, short sum)` gives `(3 + 7) = 10`  
`/r repeat (2d6, 2, sum)` gives `∑ ((1+2) = 3, (3+4) = 7) = 10`  
`/r +repeat (2d6, 2, sum)` gives `+(3+7) = 10`
