### ISSUE TITLE
Roll Two Pick Higher

### ISSUE THREAD

**Issue by jet082** [ArtemGr/Sidekick#182]
Ideally, for systems like Savage Worlds, I would like to do something like

/r (1d4! 1d6!)k1

Wherein you roll two arbitrary dice (or dice conditions - like 1 exploding d4 and 1 exploding d6) and then keep the higher of the two results.

If explosions aren't possible to keep, that's fine too (though less ideal).

**Comment by ArtemGr** [comment]
Would `/r max(1d4!, 1d6!)` work?

**Comment by jet082** [comment]
That would be lovely! :D
