### ISSUE TITLE
This seems bugged

### ISSUE THREAD

**Issue by bachman75** [ArtemGr/Sidekick#188]
If I understand the dice this should have been two successes.
![Capture](https://user-images.githubusercontent.com/50890111/58133261-74e4d780-7bf1-11e9-88e1-43753fe80332.PNG)

**Comment by ArtemGr** [comment]
"In the Storyteller and Revised Storyteller systems, successes are negated by any 1s rolled; this may result in a botch." - https://whitewolf.fandom.com/wiki/Success
