### ISSUE TITLE
Roll with advantage / disadvantage?

### ISSUE THREAD

**Issue by dyeo** [ArtemGr/Sidekick#19]
In D&D 5e, it's common to roll dice with advantage or disadvantage. Advantage is rolling 2d20 and taking the higher of the two rolls, whereas disadvantage is rolling 2d20 and taking the lower of the two rolls. It would be great to be able to roll XdY dice, and then take the highest or lowest Z dice out of the X dice rolled. For example, /r 2>4d6 would be take the greatest 2 rolls of 4d6 and add them together, and /r 3<6d12 would be take the lowest 3 rolls of 6d12 and add them together. The command syntax is up to you, but the functionality should be there.

**Comment by ArtemGr** [comment]
How about `/r 2d20kl1`? It rolls d20 twice and keeps the lowest roll.
