### ISSUE TITLE
Any way to roll great weapon master?

### ISSUE THREAD

**Issue by bunster** [ArtemGr/Sidekick#190]
Reroll a 1 or 2, forced to use the new roll even if its a 1 or 2?

I've tried /r 1d12r1r2, but that doesnt work perfectly. A 1 that rerolls as a 1 will stay as 1, but a 1 that rerolls a 2 will reroll again.

**Comment by thingy237** [comment]
brute force way, you can command to reroll the same number multiple times. unless you roll ones and twos 6 (or more) times in a row, you'll get what you need. though 1 in 50000 times will screw up. Do /r $GWM = 1d12r1r2r1r2r1r2r1r2r1r2r1r2 and use /r $GWM

**Comment by cjoll4** [comment]
I had the same issue and had to play around with it to find a solution. /r 1d12r<2 should work.

**Comment by ArtemGr** [comment]
> and keep the reroll no matter what

In practice I'm sure you wouldn't do that. You're at a table, you roll 1, reroll it to 1, reroll it to 1, reroll it to 1, reroll it to 1, reroll it to 1, reroll it to 1, reroll it to 1, reroll it to 1, reroll it to 1, reroll it to 1, reroll it to 1, reroll it to 1, reroll it to 1, reroll it to 1, reroll it to 1, reroll it to 1, reroll it to 1 and so on until the game session ends? No way.

#199

**Comment by cjoll4** [comment]
@ArtemGr I may not have worded that clearly. I don't mean "keep rerolling no matter what," I meant "keep the die that was rerolled no matter what," as in, don't reroll it again. I was just telling OP that the function /r 1d12r<2 should work for their needs.

**Comment by ArtemGr** [comment]
I see, thanks!
