### ISSUE TITLE
Bot Down

### ISSUE THREAD

**Issue by mgoosh01** [ArtemGr/Sidekick#194]
Trying to roll stats, bot is offline for past 15-20 min

**Comment by cjoll4** [comment]
I'm having the same problem, the bot has been down for more than two hours. It's offline according to Discord, and it isn't responding - neither in our server, nor to direct messages.

**Comment by mgoosh01** [comment]
Back up and rolling

**Comment by ArtemGr** [comment]
Had to regenerate the token and increase the number of shards from 32 to 64. Thanks for the heads up.
