### ISSUE TITLE
Exploding dice

### ISSUE THREAD

**Issue by ArtemGr** [ArtemGr/Sidekick#2]
2d6e -- explode indefinitely
2d6e10 -- explode up to ten times
=> Will probably stick with the roll20 syntax: https://wiki.roll20.net/Dice_Reference#Exploding_Dice

cf. https://www.reddit.com/r/discordapp/comments/4vfbqi/looking_for_a_dice_bot/d6f4so8

- [x] Pick a parser. Nom or...
- [x] Install the selected library.
- [x] Refactor how the TargetNumber works. First, in the parser, separate the basic dice (4d6) specification from the target number specification. Next, roll the basic dice right there in the parser and remember the rolls. Now, when the parser finds the target number specification - it should *apply* it to the existing rolls, marking some of them as failed. The goal here is to a) make the position matter, e.g. "4d6!6>5" (explode *then* apply DC) is different from "4d6>5!6" (apply DC *then* explode), b) simplify the code (TargetNumber becomes a Dice function).
- [x] Implement something (a function? a nom macro?) to find and replace all the matches of a nom parser.
- [x] Instead of passing the entire dice expression as a string to the dice evaluation engine - pass a representative structure from the parser.
- [x] Refactor dice replacement into one-liner.
- [x] Implement the exploding dice parsing.
- [x] Implement the exploding dice calculation.
- [ ] Tweak the output formatting.
- [ ] Unit test the parser?
- [ ] README update.

**Comment by JustLikeAMetaphor** [comment]
Hey ArtemGr!

Wanted to report a minor issue: Consecutive dice do not explode. For example, if Sidekick rolls an exploding 10, and the added dice also rolls a 10, the second 10 does not explode.

**Comment by ArtemGr** [comment]
You're right, I've overlooked this.

Filed a bug: https://github.com/ArtemGr/Sidekick/issues/7

Thanks for reporting!

**Comment by ArtemGr** [comment]
@JustLikeAMetaphor, fixed!
You can test it with "/r 1d1!".

**Comment by JustLikeAMetaphor** [comment]
@ArtemGr Just did, works like a charm!

Thank you so much, my nWoD group will love this

**Comment by ArtemGr** [comment]
You're welcome   )

**Comment by ArtemGr** [comment]
@JustLikeAMetaphor 
I'm confused with this passage in Wikipedia:

"**If another 10 is rolled, this step is repeated until anything but a 10 is rolled**"

https://en.wikipedia.org/wiki/World_of_Darkness#New_rule_system

Does it mean that if we a) roll 10, b) explode into another 10, then c) we should keep exploding until we get a 10?

e.g. "1d10" might give us "10, 10, 2, 3, 4, 5, 6, 7, 8, 9, 1, 10" = five successes (10, 10, 8, 9, 10) ?
