### ISSUE TITLE
Roll Distribution

### ISSUE THREAD

**Issue by gehnster** [ArtemGr/Sidekick#20]
Not persay an issue but.... have you looked into the distribution expected from your code with different random values for different sized die?

An article I read a couple months ago might be useful to ya.

https://msdn.microsoft.com/en-us/magazine/mt767700.aspx

**Comment by ArtemGr** [comment]
> have you looked into the distribution expected from your code with different random values for different sized die?

Some.

Here's a distribution example:
```
// Spread: {1: 9962, 2: 10012, 3: 9990, 4: 9994, 5: 9960, 6: 10191, 7: 9922, 8: 10123, 9: 9853, 10: 9992}
```
(copied from https://github.com/ArtemGr/Sidekick/issues/10#issuecomment-261319378).

> An article I read a couple months ago might be useful to ya.
>
> https://msdn.microsoft.com/en-us/magazine/mt767700.aspx

Erm, useful how?

**Comment by ArtemGr** [comment]
Would I be right to assume that the dice is playing tricks on you and you're blaming the random number generator for your luck?

**Comment by gehnster** [comment]
No tricks on me, I only fooled around with it for a couple minutes. I just wanted to make sure it was thought of instead of just assumed that it would be random.

**Comment by ArtemGr** [comment]
So you basically shared a link?

All right, thanks!

And, BTW,

> of instead of just assumed that it would be random

Sidekick is implemented in Rust and the implementors of that language tend to error on the side of quality. So yeah, I'm just assuming that the random generator is good. It's an educated guess, if you like.

Another thing to consider is that all of the random generators widely used in C, PHP, Python and whatever would be good enough to roll a d20.

**Comment by gehnster** [comment]
lol.
