### ISSUE TITLE
Bot won't join my server

### ISSUE THREAD

**Issue by gypsyred82** [ArtemGr/Sidekick#204]
2 weeks ago, we had an issue with the bot not responding so I booted him to try and get him back online.  Today I noticed he wasn't in the member list and I tried to invite him but no dice (no pun intended).  Is it down?

**Comment by ArtemGr** [comment]
The bot is online. All shards operational.

And if I had to guess I'd say that the act of adding the bot to the server doesn't even need it to be online, it's a "separate concern" so to speak.

Neither the unavailability of one of the shards would affect the presence of the bot in the member list. The bot will be in the offline section, sure, but still in the member list. There isn't any automation in Discord to remove the bots from the member list as far as I'm aware of.

Just my two cents, anyway.
