### ISSUE TITLE
Memory for Savage Worlds dice

### ISSUE THREAD

**Issue by Rimhollow** [ArtemGr/Sidekick#22]
The basic resolution mechanic for PCs in Savage Worlds is to roll a single trait (attribute/skill) die (d4 through d12) as well as a "Wild Die" (usually a d6), both of which explode; keep the highest of the two; and add any modifiers. There doesn't seem to be an official way to roll that in Sidekick, although I just learned about the undocumented "max" function from reading other issues. :) Still, ~~"max(d10!,d6!)k1"~~ "max(d10!,d6!)" is kind of a mouthful to type out for every roll.

There's a few special cases: for rapid fire, you roll one skill die for each shot, plus one Wild Die, and replace any one skill die with the Wild Die if it's better. A few abilities can make the Wild Die a different die type. Some other minor stuff, but...

Is adding abbreviations/macros for specific systems something you're willing to do? I would love something like "/r sw d10" being shorthand for ~~"max(d10!,d6!)k1"~~ "max(d10!,d6!)", with maybe "sw 3d10" for rapid fire and "sw d10w10" for an altered Wild Die. But I understand that you may not want to introduce special syntax for every system out there, and a robust macro system is not easy to engineer.

**Comment by ArtemGr** [comment]
> max(d10!,d6!)k1

This doesn't work, does it?

> Is adding abbreviations/macros for specific systems something you're willing to do?

I have plans for the bot to remember the rolls under shorthands. So if there *is* a lengthy roll that does what you need, then I'd rather focus on making it available under a shortcut.

I was going to implement it in the following way:

```
/r strength max(d10!,d6!)k1
```
Rolls and remembers the dice specification as "strength".

```
/r strength
```
Rolls strength again.

**Comment by Rimhollow** [comment]
Ah, right, sorry--I meant `max(d10!,d6!)`, which works fine. Got confused while transcribing it to Github, apparently.

Shortcuts sounds like a great idea, and should work for most Savage Worlds rolls. It would be handy to do math with them, e.g.

```
/r swd10 max(d10!,d6!)
/r swd10 +4
```

To make a d10 trait roll with a +4 bonus. Although that syntax could get confusing, as it could be interpreted as redefining "swd10" as "+4". Maybe you'd want to use `=` as an explicit assignment operator?

This is less important, but it would be handy to be able to use the "keep" syntax on groups of dissimilar dice for rapid fire, e.g. something like `/r (3d10!,d6!)k3` to roll 3 shots at d10 and replace the worst one with the d6 Wild Die if it's higher.

**Comment by ArtemGr** [comment]
> Maybe you'd want to use = as an explicit assignment operator?

Good idea!

**Comment by ArtemGr** [comment]
I think I'll mark the memorized rolls [with a sigil](https://en.wikipedia.org/wiki/Sigil_(computer_programming)), e.g.
```
/r $swd10 = max(d10!,d6!)
/r $swd10 +4
```

This will simplify greatly the task of fishing for memorized names in expression.

**Comment by ArtemGr** [comment]
Check it out.

    /r $swd10 = max(d10!,d6!)
    /r $swd10
