### ISSUE TITLE
pair programming

### ISSUE THREAD

**Issue by ArtemGr** [ArtemGr/Sidekick#221]
Hey, if someone wants to pair program on Sidekick in order to speed things up, give me a shout  D

(Either in general or on something particular, continuously or just once, all of these have a positive effect).

**Comment by gabartomeo** [comment]
Relevant question: What language is Sidekick written in? I'd be interested, but I'm not sure if it's a language I'd be decent in helping with.

**Comment by ArtemGr** [comment]
Rust!

**Comment by aloisdg** [comment]
Where is the source code?
