### ISSUE TITLE
slow response, no response, offline

### ISSUE THREAD

**Issue by inklesspen** [ArtemGr/Sidekick#232]
likely the same issue as on a lot of other bugs linked to #129.

Today I added Sidekick to a new server (server id 688211273061761058) and would generally see a minute's lag in responses.

Time reference in US pacific timezone: 2012-03-13 20:28
in UTC: 2012-03-14 05:28

---
Implementation notes: https://github.com/ArtemGr/Sidekick/blob/master/notes/232-speed.md

**Comment by ArtemGr** [comment]
Usually a Discord issue though. I'm using the bot all the time and it is staying frosty. On the other hand, some shards might be seeing Discord connectivity issues. Ideally we'd be able to know the shard of the user who's facing the trouble, but we can only know it if the user talks with the bot, and if the shard is down then a chance is that they can't talk with the bot, so it's the chicken and the egg problem.

**Comment by inklesspen** [comment]
"Ideally we'd be able to know the shard of the user who's facing the trouble, but we can only know it if the user talks with the bot"

I was talking with the bot, though, at that time reference? Is there additional info you need?

**Comment by mattcrwi** [comment]
We are also experiencing slowness. Multiple minute response times.

**Comment by Jstenoien** [comment]
Same here, 6-10 minutes.

**Comment by TashaGrn** [comment]
Yep, so bad that it it dropped many roll requests. between 2pm and continuing to now.

**Comment by ArtemGr** [comment]
There are no 6-10 minute delays in Sidekick, requests are dropped much earlier than that, so if you're seeing 6-10 minute delays - they are happening in Discord.

I've seen such delays and drops while talking with a colleague of mine.

That being said, on our side we can do a number of things: publish our shard connectivity statistics (should then be obvious if there's a drop in the number of requests coming through a shard), create a command that displays the shard number. I'm adding them to a todo list above.

**Comment by ProphetZarquon** [comment]
What about a bot to report outages to? Basically, each user talking to multiple shards; one for usage & one for QOS? Just spit-balling ideas as they occur to me

**Comment by ArtemGr** [comment]
Update: https://youtu.be/9sZJSVfRogo

**Comment by ArtemGr** [comment]
NB: Sharing small bits of progress at https://t.me/sidekick_dev

**Comment by Sancroix** [comment]
thank you.  If feedback on status is helpful, I noticed the BOT shows as Offline, approximately 3PM CST, on 20 Dec 20.

**Comment by stevenarm** [comment]
Offline for my server as well.  Noticed it on 12/20 2pm MST

**Comment by deneuvil** [comment]
Same issue noticed here at 9.13pm CET

**Comment by ArtemGr** [comment]
Thanks for the heads up, restarted

**Comment by camillescott** [comment]
FYI, Sidekick has gone offline on our server as of a half hour ago or so. Global?

**Comment by ArtemGr** [comment]
Global, couldn't fix
