### ISSUE TITLE
Sidekick Response Delay

### ISSUE THREAD

**Issue by jlrothwell** [ArtemGr/Sidekick#242]
Again on Discord there is a long response delay.  2020-04-19  die roll at 4:13 pm EST, response at 4:19 pm EST. Further delays of 5-6 minutes continued until 4:40 when we stopped due to delays.

Tried 2 other channels, delay of 8 minutes: 4:16 pm, response 4:24 pm for both the other channels.

**Comment by ArtemGr** [comment]
cf. https://github.com/ArtemGr/Sidekick/issues/238#issuecomment-610337476
