### ISSUE TITLE
Sidekick is offline for at least 7 minutes on Discord

### ISSUE THREAD

**Issue by Criddlz** [ArtemGr/Sidekick#245]

**Comment by Criddlz** [comment]
Sidekick off line for at least 8 minutes now

**Comment by Ayrtoncb** [comment]
Yeah, same thing over here

**Comment by nilamandal** [comment]
I am also having this issue. I installed Sidekick for the first time 10 minutes ago.

**Comment by ArtemGr** [comment]
cf. https://github.com/ArtemGr/Sidekick/issues/238#issuecomment-610337476
