### ISSUE TITLE
Dice rolls are duplicated.

### ISSUE THREAD

**Issue by LoganFraser** [ArtemGr/Sidekick#249]
Every dice request is being repeated. 
![double](https://user-images.githubusercontent.com/33788254/82767055-5eabc180-9dd9-11ea-9174-0a6ee0de8b93.png)

**Comment by rhaluf** [comment]
I have the same Issue :(

**Comment by sajiyoyo** [comment]
i got the same thing here.

**Comment by lamialily** [comment]
Can confirm, recently installed Sidekick to a new server and it was duplicating rolls. It still seems to be operating normally in another server.

New server's region is set to US east. Not sure what the other one is.

**Comment by ArtemGr** [comment]
Thanks for the heads up, should be fixed now

**Comment by lamialily** [comment]
Just popping in, works fine now. Thanks a ton!

**Comment by SatanInAZootSuit** [comment]
Hi, I see this issue is marked as closed but we're having the same issue in our server

**Comment by ArtemGr** [comment]
All right, detecting replica activity needed a bit of adjustment

**Comment by ProphetZarquon** [comment]
It's just started happening for me on my server; was working fine a few hours ago, then suddenly started rolling twice for every request.

**Comment by ArtemGr** [comment]
For how long it did?

**Comment by ProphetZarquon** [comment]
Sadly, I don't know. But it's working today!

**Comment by Wanderer202** [comment]
Showing same issue again, 3:15 PM EST, July 11, 2020
![image](https://user-images.githubusercontent.com/68164829/87232222-3bd66c00-c38b-11ea-922c-0568f1d07d9e.png)
