### ISSUE TITLE
'Opensource' cannot hide the code

### ISSUE THREAD

**Issue by cromlyngames** [ArtemGr/Sidekick#255]
This project is not open source.

**Comment by grepwood** [comment]
https://github.com/ArtemGr/Sidekick/blob/master/LICENSE

As per the license agreement, the license allows to obtain, redistribute and modify the code among other things. This git repository is basically violating its own license agreements by not disclosing the source code.

**Comment by hgrahamcs** [comment]
What would be the proper method of enforcing this license to obtain the source code? Personally I'd like to see how the rng is implemented for rolls as I'm encountering many duplicate rolls.

**Comment by grepwood** [comment]
@hgrahamcs lawsuit. Nothing scares people more than paying massive legal proceeds for having a judge, jury, prosecution and an advocate involved. Basically, the maintainers of this git repo are `withholding the right to deal in the software without restriction` which violates the license.
