### ISSUE TITLE
Accepts all commands in duplicate and output multiple results in return

### ISSUE THREAD

**Issue by ScienceOfMemory** [ArtemGr/Sidekick#256]
After the cloudflare outage today on July 17 2020, Sidekick has been accepting every command in duplicate, outputting double results in return. I.e. a single /r 1d100 command results in two separate 1d100 rolls by the bot. I tried kicking and re-inviting the bot, but that did not solve the issue. I quit and restarted discord, nothing. It happens to every person on my server and in every channel it is in.
I have no idea how to fix this on my end.

**Comment by ArtemGr** [comment]
BTW, never heard of kicking and reinviting the bot to fix anything.
