### ISSUE TITLE
Sidekick is delayed: 5-7 minutes until response

### ISSUE THREAD

**Issue by 5hinryuu** [ArtemGr/Sidekick#258]
Hi,

since around 20 minutes the response of Sidekick is delayed by about 5-7 minutes.

Any chance I can fix it by myself? I read you were trying giving shard restart to the users in 2018.

Kind regards

**Comment by 5hinryuu** [comment]
Edit: Seems like the issue fixed itself within the last 37 minutes.

**Comment by Ciarlini34** [comment]
Had the same issue

**Comment by ArtemGr** [comment]
#232
