### ISSUE TITLE
Morrow Project dice.

### ISSUE THREAD

**Issue by timgray** [ArtemGr/Sidekick#26]
Ok I need help as I cant figure this out on the bot.
Morrow project rolls 1D100 and your tens is successes.  so if my skill is 45 and I roll 43 I succeeded with 4 successes.
But if I roll a 44  I succeeded with 8 successes as a double number is an Exceptional success and you add both numbers together.

/r (1d100) mod 10 does not work, so what do I use to get a modulus 10?  and then how can I detect doubles?

Thanks!

**Comment by ArtemGr** [comment]
Salute!

> But if I roll a 44 I succeeded with 8 successes as a double number is an Exceptional success

So, 11, 22, 33, 44, 55, 66, 77, 88, 99 - all are exceptionals?

> /r (1d100) mod 10 does not work, so what do I use to get a modulus 10?

/r 1d100 % 10

**Comment by timgray** [comment]
Yes 11,22,33,44,55,66,77,88,99 are all exceptionals.

**Comment by ArtemGr** [comment]
Well, we're kind of close to detecting these with a modulo, e.g.
/r 11 % 11 = 0
/r 22 % 11 = 0
/r 33 % 11 = 0
and so on.

But to do it automatically and in one "roll" you'd need something more complex than plain math, either a system with variables and conditions or a function specifically tailored to support Morrow Project.
