### ISSUE TITLE
Hero Quest combat dice - is there a command to replicate their probability?

### ISSUE THREAD

**Issue by michael-niemand** [ArtemGr/Sidekick#267]
In Hero Quest there are 6 sided combat dice with 3 symbols, each with a different probability:

https://www.heroscribe.org/hqdice.png
![image](https://user-images.githubusercontent.com/12845693/96375934-6602ab80-117c-11eb-9b4e-d1d965f6d0d8.png)

Can this behaviour be replicated with a Sidekick command?

**Comment by nightpool** [comment]
The easiest way I can imagine to do so would be to roll 1d6 and then say 1 = black shield, 2-4 = skull, 5-6 = white shield. Not the most elegant system, but probably the simplest?

**Comment by michael-niemand** [comment]
yeah that's what my wife suggested, too - sometimes the simple solutions are the best.
