### ISSUE TITLE
Add labels to rolls

### ISSUE THREAD

**Issue by treetrnk** [ArtemGr/Sidekick#27]
It would be nice to be able to label a roll in the actual roll command. One way to do this is by requiring that no spaces are used within the equation. Then you can separate the command by spaces, allowing anything after the second item to be a text label for the roll. For example:

The command: 
`/r 1d20+2 Con Save`

The output:
`Con Save: 1d20+2 = (20)+2 = 22`

Not a necessity by any means, but it is nice to be able to say what your are rolling as you roll it rather than sending a separate message.

**Comment by treetrnk** [comment]
Ooops, I missed that this was already implemented. Disregard please!

**Comment by ArtemGr** [comment]
Hey. Thanks for coming by.

> /r 1d20+2 Con Save

I had something like this at first, but then I thought about all the weird stuff we might need to do with the [dice notation](https://en.wikipedia.org/wiki/Dice_notation) and decided that we need to cleanly separate the comment from the body at first, in order not to confuse the parser even further.

Long story short, the comments hide behind a hashtag now.

**Comment by ArtemGr** [comment]
Hohoho, a fellow bot writer!
@treetrnk, I'm planning to roll out a Telegram version of the Sidekick bot as well. Had the Telegram hooks working for a different bot project for a long time now, it's just a matter of rewiring a function or two. Though dice rolling won't be a priority for a while.
