### ISSUE TITLE
Sidekick bot offline

### ISSUE THREAD

**Issue by gkern00** [ArtemGr/Sidekick#271]
The discord bot has been offline for almost an hour

**Comment by rvaessen** [comment]
My server (Name: RobsWorld! / Number: 698888154819723275 / Region: US West) is experiencing the same condition. The bot is Offline. It doesn't respond to commands in monitored channels (where it has permissions), and it doesn't even respond to Direct Messages. I tried changing regions (now on US Central), and restarting Discord with same results. Sidekick#6198 is Offline here as well. I have not tried kicking and re-adding the bot. I don't have time to do that right now.

**Comment by Huntess** [comment]
Bot went offline on a server im in as well. in a Europe server.

**Comment by rvaessen** [comment]
I've been a bit busy over the last few days... but I notice (as of 27 Nov, 2020) that the sidekick bot is back online (I see it online/awake/it's alive!) and answering die roll commands in a monitored text channel on my Discord server instance. I'm not sure when it came back.

**Comment by kiloforce** [comment]
Seems to be offline again.

**Comment by ArtemGr** [comment]
Dedup
