### ISSUE TITLE
No response

### ISSUE THREAD

**Issue by SirRayne** [ArtemGr/Sidekick#274]
It will no longer roll, or do anything. I'm a little disappointed actually. I have Pathfinder tonight, and it's my only dice not right now. I have been using it for months with no issues, but if it isn't fixed, I'll have to find another.

**Comment by elvoreis** [comment]
Same issue here. It was working fine yesterday, but today it doesn't doing anything. It's still showing as online and no server changes have been made.

**Comment by ArtemGr** [comment]
Duplicate of #232
