### ISSUE TITLE
Bot is down

### ISSUE THREAD

**Issue by ninjamike808** [ArtemGr/Sidekick#276]
Bot is down. It’s like it’s offline. I can’t tell you much more than that.

**Comment by DeltaCain** [comment]
Bot is still down.

**Comment by ArtemGr** [comment]
thanks for the heads up

**Comment by ninjamike808** [comment]
Still doesn’t work for me, but at least it appears online

**Comment by Sancroix** [comment]
I see the issue # is closed, so this is just feedback. The bot's behavior on my server is similar, in that it shows Online, but not responding to /r requests.
