### ISSUE TITLE
It is not working properly.

### ISSUE THREAD

**Issue by Kuroshiwa92** [ArtemGr/Sidekick#277]
The bot is online but does not respond to any command.

**Comment by leo4459** [comment]
I'm having the same problem

**Comment by grimsqueaks** [comment]
same

**Comment by Sancroix** [comment]
As well. Discord server is in US. I don't know if this helps; I've moved around the different US regions (South, East) and seen no change in behavior.

**Comment by SUTempest** [comment]
Can confirm. Unresponsive on multiple servers here as well.

**Comment by Pa-Mar** [comment]
Same problem: we played for two hours in a row and I handled the (luckily few) rolls needed by rolling actual dice - I am the GM and my players trust me.

At the very start of each session I always do a couple of rolls just to be sure that the Macros we created did not expire (happened once months ago) and noticed that no matter what, the bot was basically dead: no error message, no output of any kind. Tried macros and normal rolls, tried to re-invite it.
