### ISSUE TITLE
Sidekick offline for a day now

### ISSUE THREAD

**Issue by rinandstyx** [ArtemGr/Sidekick#286]
Sidekick has been offline for a day now, is there any way i can trouble shoot this myself in the future? Or is it something that needs to be reset?

**Comment by Sancroix** [comment]
Logging in to confirm my use of the bot is also 'offline'. 14 Feb 2021.

**Comment by SUTempest** [comment]
Sidekick's likely down for good. Don't bother. https://www.patreon.com/posts/rip-47477208
