### ISSUE TITLE
Open source Sidekick

### ISSUE THREAD

**Issue by nightpool** [ArtemGr/Sidekick#287]
If Sidekick does end up going down for good, would you be okay with open sourcing the code so other people can run their own instances of it? Sidekick is still the best dice-rolling bot for the features I use it for, and I'd love to be able to continue using for the 3-5 servers I use it in, even if I have to support future API changes myself.

**Comment by ArtemGr** [comment]
Not currently interested in publishing pronto the old code. If someone wants to help with a pluggable JS engine / architecture, then the old Sidekick might be republished as one of the JS plugins.
( cf. `Pluggable` in https://github.com/ArtemGr/bounty/blob/main/notes/my-net.md )
