### ISSUE TITLE
dicebot offline

### ISSUE THREAD

**Issue by onionvoid95** [ArtemGr/Sidekick#30]
the dicebot is appearing offline at the moment? is this another server issue or is it something else?
![image](https://cloud.githubusercontent.com/assets/26127830/23488593/ace48140-febb-11e6-996d-a3a2537527e4.png)
this is how it appears on both of the servers i use it on?

**Comment by kaeroku** [comment]
Offline here too.

**Comment by ArtemGr** [comment]
Sorry about that.
There were connectivity issues on the server.

Unfortunately we do not automatically reconnect after the connection to Discord servers goes down for some reason. I shall fix this.

**Comment by onionvoid95** [comment]
It's alright, thank you very much for your efficiency. It's appreciated.
Ovao

**Comment by ArtemGr** [comment]
So I ended up implementing a true High Availability failover.
A separate instance of the bot (the *standby*) keeps the shards open and monitors the *primary*, getting to work as soon as the *primary* shows any kind of a problem.
The same health monitoring mechanics is also used to restart the bots when they no longer receive events from Discord.

Here's a little article I wrote: https://www.reddit.com/r/discordapp/comments/5xjqia/the_bots_on_high_and_available/
Please vote up  )
