### ISSUE TITLE
Proper re-roll syntax

### ISSUE THREAD

**Issue by ArtemGr** [ArtemGr/Sidekick#31]
Like Elegant427 pointed out, our re-roll documentation is incorrect. We only have the exploding dice syntax. Re-roll is different from exploding dice in that it excludes the rerolled dice from the total sum.

To quote:

---
So, instead of getting exploding 1's
    repeat(3d6[explode]1, 6) = (3+5+1+6) = 15, (1+3+2+4) = 10, (1+5+2+6) = 14, (1+6+4+5) = 16, (6+3+5) = 14, (4+2+1+2) = 9
A 're-roll' function would show something like
    repeat(3d6[re-roll]1, 6) = (3+5+~~1~~+6) = 14, (~~1~~+3+2+4) = 9, (~~1~~+5+2+6) = 13, (~~1~~+6+4+5) = 15, (6+3+5) = 14, (4+2+~~1~~+2) = 8

---

As usual, roll20 has a syntax for us: https://wiki.roll20.net/Dice_Reference#Rerolling_Dice

**Comment by lucifronsun** [comment]
Sorry if this counts as a necro, but it seems there still isn't an ability to do rerolling. Is this still a planned feature?

**Comment by ArtemGr** [comment]
You can use `/r 3d6r1` now.

It's limited to one re-roll per dice, currently.

For D&D halfling's luck it might be neither here nor there, we might limit to one re-roll per combination instead: "*When you have advantage or disadvantage and something in the game, such as the halfling's Lucky trait, lets you reroll the d20, you can reroll only one of the dice. You choose which one. For example, if a halfling has advantage on an ability check and rolls a 1 and a 13, the halfling could use the Lucky trait to reroll the 1.*"
Still, rerolling once per dice seems like a sensible default, rerolling more might look artificial and complicate the rolls unnecessarily.
