### ISSUE TITLE
Use a license better suited to documentation

### ISSUE THREAD

**Issue by bmintz** [ArtemGr/Sidekick#33]
According to #32, the devs have no interest in making the code open source. Since this repo is apparently for documentation only, please use a license written for non-code creative works, such as CC-BY.

**Comment by ArtemGr** [comment]
First, I'm okay with the familiar MIT license.
Second, I'm often posting code snippets inside the issues. I would prefer to think that they fall under the project's license.
Third, I don't see a reason why I should preclude myself from open sourcing a part of the project in the future.
Fourth, you're basically wasting my time. If this repository is a soar in your eye then I propose we solve the problem by me blocking you. You won't be able to see this repository then, problem solved.

**Comment by ArtemGr** [comment]
Done and done.
