### ISSUE TITLE
Abnormally high 10's In Cronicle of Darkness Rolls (/r 10d10>=8

### ISSUE THREAD

**Issue by Takasango** [ArtemGr/Sidekick#36]
Server Requiem for Greece

Hello we have a larp server with about 80 users. We use your bot for dice rolling and we are noticing a predisposition towards tens. 

Maybe its nothing but can you look into into from our logs? Tell me what else you need to make the tests.

Thanks in advance for any help.

**Comment by ArtemGr** [comment]
That's the point of random numbers, they can give you streaks of good or back luck.
Statistical distribution starts to kick in on a larger scale. There's a bit on it here, IIRC: http://theangrygm.com/probability-for-gamers/
See also https://github.com/ArtemGr/Sidekick/issues/10

**Comment by ArtemGr** [comment]
To quote Angry: "*The point is statistical analysis and probability let you make some guesses about what is likely and what isn’t and they let you make broad statements about a population. But any given individual result is still down to random chance. And you can’t use statistical tools on individuals.*"

**Comment by Takasango** [comment]
Thanks a lot for your attention!

I knew as much but wanted to be sure!

**Comment by ArtemGr** [comment]
You're welcome!   : )
