### ISSUE TITLE
Deleting saved rolls

### ISSUE THREAD

**Issue by BuncyTheFrog** [ArtemGr/Sidekick#39]
We can save dice rolls with /r $\<nickname\> = \<dice roll\>. I don't see a way to delete them and free up saved roll space.

I tried issuing "/r $\<nickname\> =" in hopes that it would "unset" the roll using that, to no luck.

Can you please either document the method in the readme, or add one (and document it)?

Thanks!

**Comment by ArtemGr** [comment]
So this feature was only added last week, roll removal isn't implemented yet, I will fix it soon. Thanks for the heads up!

**Comment by ArtemGr** [comment]
You can now list the memorized rolls with `/r $` and remove them with `/r $name =`.

**Comment by Tarliman** [comment]
The listing stops after the first 25 rolls.


On 07/09/2017 01:02 PM, Artem wrote:
> You can now list the memorized rolls with |/r $| and remove them with 
> |/r $name =|.

-- 
Andrew W. Ragland
andrew.ragland@gmail.com

**Comment by ArtemGr** [comment]
It must be a Discord limit.
Please try again, I have updated the bot to send multiple embeds.

**Comment by Tarliman** [comment]
Fixed, thanks.


On 07/09/2017 01:21 PM, Artem wrote:
> It must be a Discord limit.
> Please try again, I have updated the bot to send multiple embeds.

-- 
Andrew W. Ragland
andrew.ragland@gmail.com

**Comment by ArtemGr** [comment]
You're welcome. Thanks for testing it on a short notice.
