### ISSUE TITLE
Variable failure condition?

### ISSUE THREAD

**Issue by EricTheSpider** [ArtemGr/Sidekick#44]
I see that you have implemented oWoD (/r 3d10>=6f1) as one of the dice rolling variations. I have experimented with the command and whilst the size of the die can be varied I have been unable to adjust the failure condition sucessfully.

The whilst changing the number after the f will change the number that consititutes a failure I have been unable to get it to treat multiple results as a failure. For example I would like to be able to roll multiple d10s and treat 9 and 10 as a success, but 1,2 and 3 as failures (for example).

If this is not already implemented would it be possible to do this, or if it is (as I suspect) user error can you confirm the correct format for the command?

**Comment by dashifen** [comment]
it would also be interesting to use something like this for Shadowrun's glitch mechanics (e.g. rolling more than 50% of your dice pool as ones -- or in some cases ones and twos).

**Comment by ArtemGr** [comment]
Backed by Cerxi.
