### ISSUE TITLE
Bot isn't responding in main channels?

### ISSUE THREAD

**Issue by oconnor0** [ArtemGr/Sidekick#50]
I used the link to install Sidekick on my server, and it worked yesterday, but today it's not responding in public channels only when I DM it.

**Comment by ArtemGr** [comment]
It's working on my side. Could have somebody [blocked](https://support.discordapp.com/hc/en-us/articles/217916488-Blocking-Privacy-Settings-) it?

**Comment by oconnor0** [comment]
Hm. I'm not seeing anything like that. I see it online. I know I "Mute"d it yesterday, but unmuting it today hasn't changed anything.

**Comment by ArtemGr** [comment]
I suspect that "Mute"ing might be an issue.
Have you tried removing the bot and then adding it back to the server?

**Comment by oconnor0** [comment]
Yeah, I kicked and re-added it. No luck.

Is https://camo.githubusercontent.com/e35a7b3419f41d3cd9c7ab9e41aa9402d786216a/68747470733a2f2f626c6f6f6b732e746f6461792f722f736964656b69636b2d736572766572732e676966 supposed to be down?

**Comment by ArtemGr** [comment]
I've restarted the bot, maybe it'll help.
If it doesn't, you can send me an invite and I'll check a few things tomorrow.
Also see if you've changed [verification level](https://support.discordapp.com/hc/en-us/articles/216679607-What-are-Verification-Levels-) of your server, I see a couple of errors around that in the logs.

**Comment by oconnor0** [comment]
Looks like it's working now. Thanks. :)

**Comment by ArtemGr** [comment]
Coolio.
