### ISSUE TITLE
Bot Offline

### ISSUE THREAD

**Issue by Picklek** [ArtemGr/Sidekick#51]
Soo.... Yeah it's offline for me, anyone else having the same problem?
![image](https://user-images.githubusercontent.com/29557527/27311314-fd25d5d2-5514-11e7-887b-a46655be85a2.png)

**Comment by ArtemGr** [comment]
Sorry about that.
Restarted...
Better now?

**Comment by Picklek** [comment]
Yes, much better thank you! ^^"

**Comment by ArtemGr** [comment]
I'll try to figure what's up with the outages.

**Comment by ArtemGr** [comment]
Should be fixed now, cf. https://www.patreon.com/posts/broken-mirror-15681433
