### ISSUE TITLE
Sharing memorized rolls

### ISSUE THREAD

**Issue by Tarliman** [ArtemGr/Sidekick#55]
I've built the Step Table for FASA's CoreStep mechanic, which required creating 50 memorized rolls. How do I share these with other people in the channel, so that they don't have to build them from scratch themselves?

**Comment by ArtemGr** [comment]
Sounds cool!

Sharing the rolls is something I'm still thinking about.
Would you PM me a server invite so that I could debug this feature on the meaningfull data?

**Comment by Tarliman** [comment]
Not sure how to PM on Github, and I don't have your Discord ID number, but our server is public, so https://discord.gg/W72URea

**Comment by ArtemGr** [comment]
Also discussed at https://github.com/ArtemGr/Sidekick/issues/56
