### ISSUE TITLE
NWOD "Exploding die" only explodes the first die set when configured for 9-again

### ISSUE THREAD

**Issue by inucune** [ArtemGr/Sidekick#62]
Issue:
NWOD format only explodes (rolls) 1 additional dice set when configured for 9-again.

Steps to recreate:
Run the following command and look for more than 1 set of exploded(9 or 10-on-roll) dice.

/r 10d10>=8!9

![image](https://user-images.githubusercontent.com/12404410/28252074-b84ab62e-6a51-11e7-834c-5f431e51a791.png)

the expected output would be
the first 10 dice:
3 8 9* 4 2 5 2 2 5 10*
2 exploded dice rolls:
9* 8
an additional exploded roll from the 9
[missing]

**Comment by Alkius** [comment]
Your roll code just needs a little fiddling.

/r 10d10!>9 >=8

![exploding9s](https://user-images.githubusercontent.com/32929170/31768294-92e34e92-b483-11e7-9656-399f17b1b8af.JPG)

**Comment by inucune** [comment]
Operator error. see above.
