### ISSUE TITLE
list "/r $" command not working

### ISSUE THREAD

**Issue by Ahrrrr** [ArtemGr/Sidekick#64]
Hi, Great fan of your bot. 

Tried the command
/r $wk4 = max(1d6!, 1d4!)

I could use 
/r $wk4
and it work fine

but not working is 
/r $
as i understand it should list the saved command. but it does not.

Having another command saved like
/r $blink = 2d20!

is working and showed as expected when "/r $" is send

So there is a maybe problem with the **max(..)** or the number in the name (wk**4**)

Keep up the good work

**Comment by ArtemGr** [comment]
Hey, @Ahrrrr! Thanks for the heads up.

> So there is a maybe problem with the max(..) or the number in the name (wk4)

It's not that simple, unfortunately.
Looks like the database replicas are getting out of sync. We have your rolls on one replica but not the other.

**Comment by Ahrrrr** [comment]
Good Morning @ArtemGr 
Thank you for the Reply. Sounds like a problem that is not easy to solve. 
The saved rolls are still working, even when they are not visible. 
I made s sticky comment with the calls so it will work for me. 

So thank you for the bot and sorry that i could not help. 

With Kind Regards
Ahrrrr

**Comment by ArtemGr** [comment]
Guess I'd have to switch to the usual master-slave replication, given that BDR isn't very reliable yet.
Will be setting up a new database server soon.

**Comment by Ahrrrr** [comment]
That would be nice. 
Looking forward to it. *thumbsUp*

**Comment by OzoneGrif** [comment]
Just testing your bot today, superb idea!
The macro system doesn't seem to work at all. We are playing WtA and since the roll is a bit long ( /r Xd10>=Yf1 with X and Y the only numbers changing), I was trying to create simplier macros like /r $X_Y for the whole channel. Not sure they are shared between all the members tho. Shared macros (on the whole server) would be awesome.
Thanks again.

**Comment by ArtemGr** [comment]
@OzoneGrif 
Glad to hear that! Shared macros are next on the plate once I fix the database.

**Comment by ArtemGr** [comment]
Should be fixed. Moved the database to a fresh PostgreSQL 10 box.
