### ISSUE TITLE
Memorized Rerolls?

### ISSUE THREAD

**Issue by nesges** [ArtemGr/Sidekick#66]
Maybe I'm getting the memorize function wrong - I excpected it to save the result, instead it saves the number of dice and rerolls them:

```
 /r $initiative = 4d20
 
 @nesges: $initiative 4d20  = (15+9+6+12) = 42
 
 /r $initiative
 
 @nesges:  $initiative  = (15+19+8+5) = 47
```

Is this working as intended? If so, I'd like to ask for a variant that memorizes the result instead :-)

**Comment by ArtemGr** [comment]
Yeah, it works as intended.
If you want to memorize 42, you can do "/r $initiative = 42", right?
