### ISSUE TITLE
Bot casts spells?

### ISSUE THREAD

**Issue by Friend-of-Ollie** [ArtemGr/Sidekick#70]
I added Sidekick less than 24 hours ago to our Discord because our regular dice server is dead, and Sidekick has proven to be a great tool to use instead. However, it randomly yelled "Reducto!" at one of the Discord members and I'm kinda baffled as to why.

Any explanation would be greatly appreciated!

EDIT: It's been casting more HP spells, while I'm not worried as such, it was never specified it did that on the instructions.

**Comment by ArtemGr** [comment]
Hi!

The bot is prone to throw a random spell at you if it failed to understand you. Talk about bad temper.

I'm sorry, I blush or cough every time it misbehaves, but I have no other.
