### ISSUE TITLE
/r 1d1.5

### ISSUE THREAD

**Issue by arcandio** [ArtemGr/Sidekick#75]
I was just experimenting, and it seems that d1.9, d1.5 and other 'decimal dice' are valid, but are parsed funny:

```
2d2.9  = (1+2).9 = 3.9
```
Decimal dice don't make sense, so I figured they should probably throw an error or something, unless this is used for a notation I'm not familiar with.

**Comment by ArtemGr** [comment]
Good catch.

Sidekick generally works in two stages: first the dice is processed and then the math.
What you're seeing is the dice results (2d2 = 1+2) being processed by the calculator.

This might change if we would actually treat the dot as a part of the dice notation, but I see no big harm in leaving it as is.
