### ISSUE TITLE
Dicebot offline

### ISSUE THREAD

**Issue by mgoosh01** [ArtemGr/Sidekick#76]
Attempting to roll for a tabletop game, no response from the bot when command is input. 

[Image of the commands](http://i.imgur.com/AdmxEaW.png)

**Comment by ArtemGr** [comment]
Restarting. Did it help?

**Comment by mgoosh01** [comment]
Yup, that seemed to fix it!

**Comment by ArtemGr** [comment]
All right, thanks for the heads up.
