### ISSUE TITLE
[Suggestion] Method to suppress formatting and/or separate rolls in one line

### ISSUE THREAD

**Issue by thegreatersea** [ArtemGr/Sidekick#79]
I'm currently running an In Nomine campaign on my server, and I've been having trouble finding a good format for In Nomine's special d666 system (roll 3 d6, first two are summed and the third is not). I was originally using "/r 2d6+1d6" because the formatting paired the first two dice, but it still summed the whole roll (not a bug, but not what I'm going for). The repeat command works wonderfully, but it also adds unnecessary formatting to the result (ex: repeat (1d6, 3)  = (3) = 3, (6) = 6, (2) = 2). I'd like to request either the ability to have multiple rolls in one command that aren't summed (something like "/r 2d6;1d6" outputting "(3+6) = 9; 2), or a modifier that causes sidekick to just list the results (ex: "/r repeat (1d6,3)list" would output "3, 6, 2"). While a command just for In Nomine's system would of course be appreciated, I understand that not many people play this system and the feature would likely be underused.

**Comment by ArtemGr** [comment]
1 1 1, sir.

/r repeat (d6, 3, list)
/r repeat (d6, 3, short)
/r repeat (d6, 3, brief)
should work.

> While a command just for In Nomine's system would of course be appreciated, I understand that not many people play this system and the feature would likely be underused.

You might be able to do that with #55 once I implement it.

**Comment by kellyRocket** [comment]
I'd actually like this, as sort of a general use thing, that will sort any comma separated list of numbers.

So something like /r sort ( repeat (4d6k3, 6, brief )  ) 

Would give you a sorted list of ability scores for D&D, for instance. Or you could use it on arbitrary mathematical constructs:

/r sort ( (3+7), (2-2), (9^2) )

and so on.

Additionally, a keep/drop notation that worked on such arbitrary lists would also be handy.

/r sort ( repeat (4d6k3, 7, brief)k6 )

For instance, would generate 7 ability scores, drop the lowest, and then present them in order.
