### ISSUE TITLE
No limit to amount of dice?

### ISSUE THREAD

**Issue by calebbernard** [ArtemGr/Sidekick#8]
I commanded a roll of 9,999,999 dice and it hung the bot for about 6 minutes. It doesn't appear to limit number of dice.

**Comment by ArtemGr** [comment]
Yeah, I've noticed, as I've happened to had the log console open at the time.  = )

Results of this roll take 189 MiB in the log.

```
dice] input '9999999d999999999' -> rolled '(146500651+224603065+597640614+465125733+824739944+404707011+158023407+738016084+973597277+747016218+536577284+323911737+370106232+46989427+197926882+201505121+774162354+625248777+720091890+752470938+220060888+700656732+309697953+271191964+358535996+662978624+538677395+429089469+521289514+869560260+217113629+449797867+14295605+997502332+853616376+972887879+702294363+576156540+865294608+108365973+281142201+276358441+274499685+909584922+758801926+952146056+355680811+397769590+270699967+648676246+951014628+246639509+632943885+988809762+150351563+729464006+754231568+447024051+747683721+965696646+169738165+642119554+774093350+324943965+612557712+472024274+385751298+675769826+71121801+807570524+383102090+35049111+...
```

Thanks for reporting.

Introducing some limits is in the plans but they're not the top of the list as of now. Working hard on some new features for the bot.

**Comment by ArtemGr** [comment]
BTW, Discord limits the number of characters the bot can send. Not going past that limit is going to be a priority.

**Comment by ArtemGr** [comment]
Okay, there is now a hard limit (100000) on the number of dice per roll.

As I've mentioned above, you won't see results of any sufficiently large number of rolls because of the Discord message size limit. Fixing that is still in the plans but not a part of this issue.
