### ISSUE TITLE
Roll saving unusable in categorized channels

### ISSUE THREAD

**Issue by VNilla** [ArtemGr/Sidekick#81]
Hey, some friends and I had started using Sidekick for a FATE game for about a week when Discord updated on mobile and started causing problems.

They implemented a feature where channels could be filed into "categories." (The feature can be seen on desktop, but can't be used quite yet.) If a channel is in a category, Sidekick considers it a "private channel" and prevents all use of saved rolls. You can't save new rolls, or recall rolls saved earlier. Uncategorized channels still work just fine.

Any chance of this getting fixed easily, or is this a thornier issue?

**Comment by VNilla** [comment]
Update Oct. 4th: Problem seems to have resolved itself. Possibly caused by a backend update to Discord, or there is some form of 1-week waiting period required.

**Comment by ArtemGr** [comment]
Glad to hear! I wouldn't be surprised if it we a Discord issue.

**Comment by VNilla** [comment]
Oct. 5th, issue has returned, this time with no known event that could have caused it.

**Comment by ArtemGr** [comment]
I'm working on upgrading the Discord driver that the bot uses. Hopefully I'll finish soon and will be able to look into the issue you're having.
I'll need an invite and for you to point me at a channel where I can experiment talking with the bot. Try to PM me at artemciy_dice#0049.

**Comment by VNilla** [comment]
After experimentation, the issue seems to be resolvable by ensuring that the bot (or @everyone) has "Send Messages" permission set to CHECKMARK.

**Comment by ArtemGr** [comment]
See also https://github.com/ArtemGr/Sidekick/issues/46#issuecomment-323557124.
We need to document the required permissions probably.

**Comment by VNilla** [comment]
"Send Messages" seems to be sufficient, but Read and Send should be a safer catch-all.

**Comment by ArtemGr** [comment]
I've a very minimal support for category channels in https://github.com/ArtemGr/discord-rs/commit/ab9787a9e864b1954252f94a5f8b2900227c54f8. There's a small chance that it will help (we were getting a parse error in the Discord driver for such channels before, now that the error is fixed maybe the messages would have a better chance of coming through to Sidekick).
