### ISSUE TITLE
Sidekick appears to be offline.

### ISSUE THREAD

**Issue by Hawdkoah** [ArtemGr/Sidekick#88]
I've been having issues with it going offline for the past hour or two. It came back online for a few minutes, but it wasn't responsive to any commands and went back offline almost immediately after that and has been offline ever since.

**Comment by ArtemGr** [comment]
Hey, @Hawdkoah !

Looks online to me.

Discord sometimes having issues.
Let me restart the shards, it might help.

**Comment by Hawdkoah** [comment]
Looks like that fixed it. Thanks!
