### ISSUE TITLE
Bot not responding

### ISSUE THREAD

**Issue by Kalisalos** [ArtemGr/Sidekick#89]
First off, I love your bot and it's been working quite well for months now.
Today though, it just completely stopped working in one server (no answers to any prompts at all), and I have no idea why. Still shows online, and no permissions were changed at all since the last time it worked, so I have no idea what the problem is. I've tried kicking and reauthorizing the bot or giving it Admin permissions, but nothing seems to work. It does still work fine in other servers, including a test one I just created and installed the bot in. Not sure what else to try...

**Comment by ArtemGr** [comment]
Usually this kind of problem will be solved with a bot restart, but I've just finished configuring a gradual shard auto-restart (cf. https://www.patreon.com/posts/broken-mirror-15681433), so please check in a few hours and tell me whether it's working, if it's not too much trouble.

It it isn't working by tomorrow, then I'd have to investigate closer, probably asking you for a server invite.

**Comment by Kalisalos** [comment]
It's working again! Thanks!
