### ISSUE TITLE
Where's the code?

### ISSUE THREAD

**Issue by inklesspen** [ArtemGr/Sidekick#9]
You've got a MIT license up, but no code.

**Comment by ArtemGr** [comment]
There's no code yet, just the docs.

**Comment by inklesspen** [comment]
I'd much rather fork and improve the code.

**Comment by ArtemGr** [comment]
Have something specific in mind?

**Comment by inklesspen** [comment]
My [IRC dicebot](https://github.com/inklesspen/alea) supports Feng Shui exploding dice, ORE dice, Fate dice (and Fate points), and shuffling and dealing from decks of cards.

I'm particularly interested in adding support for [Unbound](https://www.kickstarter.com/projects/gshowitt/unbound-rpg/description).

But it's moot, since "there's no code yet", I guess.

**Comment by ArtemGr** [comment]
Funny, you have the code but no docs  = )

Provided there's a real interest, I can refactor the dicing code into a file here. It's written in Rust. But there's a question of the syntaxis, I've touched it some in https://www.reddit.com/r/discordapp/comments/53hdz1/wod_support_landed_in_sidekick/

**Comment by inklesspen** [comment]
Sorry, I only work on open source projects.

**Comment by ArtemGr** [comment]
I'm not here to pass judgement your beliefs.  = )

**Comment by gehnster** [comment]
If you aren't going to provide the code then you should remove the license.
