### ISSUE TITLE
[Suggestion] More detailed in-Discord command help/documentation

### ISSUE THREAD

**Issue by samsaksfithian** [ArtemGr/Sidekick#93]
It would be nice to see more examples of specific commands and things the bot can do while still in Discord and just using the Help command. A good example would be how this other RPG/Dice rolling bot does it: https://github.com/Gawdl3y/discord-rpbot

**Comment by ArtemGr** [comment]
> A good example would be how this other RPG/Dice rolling bot does it: https://github.com/Gawdl3y/discord-rpbot

I don't have that bot. Can you post a screenshot?
Any specific examples you want to be added?

**Comment by samsaksfithian** [comment]
Yes, sorry, didn't see your reply. Here you go! 
<img width="614" alt="rpbothelpdocumentation" src="https://user-images.githubusercontent.com/8661475/35347313-cdf7d0e0-0102-11e8-9150-47043185989b.png">

As for stuff to put in it, the documentation you have in the readme here on Github (other than how to install it, obviously) is good, it would just be nice for it to show up actually in Discord when you type "help" like RPBot does.

**Comment by ArtemGr** [comment]
There's some Markdown support in Discord, so I could try to output the contents of the https://github.com/ArtemGr/Sidekick/blob/master/README.md in the `/r` help output.

But we can't send messages larger than 2000 bytes long, so I'd need to page it.

**Comment by gothate** [comment]
Even just returning a link to the github readme would be a great first step and super easy.

**Comment by ArtemGr** [comment]
A link to readme we have.

![image](https://user-images.githubusercontent.com/41847/77600293-820cda00-6f18-11ea-8552-110255e91ce8.png)

**Comment by gothate** [comment]
Oh nice! It's a little tricky to get to since slash commands try to autocomplete to discord's nearest guess of what it thinks you were typing, so you have to slash-r-space. /r help being an alias for that would be super helpful.
