### ISSUE TITLE
[Suggestion] Roll with floor / ceiling option

### ISSUE THREAD

**Issue by Ixadias** [ArtemGr/Sidekick#96]
Have an option to roll with a floor, like `/roll 3d6f3`, which would roll 3d6 and any value less than 3 would be floored to 3. Vice versa for ceiling (though ceiling has a lot less practical applications than a floor).

**Comment by ArtemGr** [comment]
Hey, @Ixadias .

> though ceiling has a lot less practical applications than a floor

Any examples of how this can be used?
Game systems?

**Comment by sargteapot** [comment]
lets say dnd- you have a ability not to roll lower than x so you can roll /r 1d20fx where x is the lowest 
if x= 5 and you roll a 2 it automaticly makes it a 5,

you can limit the top by rolling lower

**Comment by ArtemGr** [comment]
> so insted of 0-20

It's 1-20, inclusive.

There is no dice with a face of zero.

> its 5-20

You can probably do this with
```
/r max (d20, 5)
```
