### ISSUE TITLE
I`m sorry if it's a silly question, but your code isn't open, right?

### ISSUE THREAD

**Issue by Allanfranc** [ArtemGr/Sidekick#98]

**Comment by ArtemGr** [comment]
Some of it is.

**Comment by merlinpatt** [comment]
What's your reasoning for keeping it closed source?

I'm curious because I would like to contribute

**Comment by InfamousMrS** [comment]
I was wondering about this too. I wanted to read your code and maybe use your service, or launch my own instance. But it was just a readme.

I have trouble trusting something like this on my discord server w/o reading the code. I can't imagine why it is closed source.

**Comment by joshuakb2** [comment]
> Some of it is.

But none of it seems to have been made available. Only the readme, license, and changelog, none of which are code... how can it be open if it isn't available?
