### ISSUE TITLE
dice rolling low 

### ISSUE THREAD

**Issue by sargteapot** [ArtemGr/Sidekick#99]
so we play dnd using this dice bot but we find after many many sesh that we roll very low much more often than anything higher than 10

**Comment by ArtemGr** [comment]
Random != uniform. What you're seeing is called _luck_.
cf. https://github.com/ArtemGr/Sidekick/issues/10#issuecomment-289076899

There are examples of luck going the other way. From today's Sidekick mention logs:
```
Archipelago (Roleplay), nation-setup, Imperator] Sidekick rolls unsually high
```
